layout_spectrum: 0.4198988
color:
  saturation: 0.3859843
  lightness: 0.7908787
  brandStrength: 0.7528889
  rhythmicContrast: 0.501348
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.5678325
name: Beacon StreetPartners
